# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20160112_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('writingfile', models.FileField(upload_to='static/file')),
                ('author', models.CharField(max_length=128)),
                ('publish_date', models.DateField()),
                ('category', models.CharField(max_length=128)),
                ('state', models.IntegerField(blank=True, choices=[(0, '\u672a\u4ed8\u6b3e'), (1, '\u672a\u5ba1\u6838'), (2, '\u6279\u6539\u4e2d'), (3, '\u7ec8\u5ba1\u4e2d'), (4, '\u5df2\u5b8c\u6210')], default=1, null=True, verbose_name='\u72b6\u6001')),
            ],
        ),
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ImageField(upload_to='image/%Y/%m/%d/'),
        ),
    ]
