# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20171113_1321'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WritingProject',
            new_name='WritingTask',
        ),
    ]
